'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Rocket, Check, ShieldCheck, Smartphone, KeyRound, ArrowRight, Sparkles, Zap,
  RefreshCw, Target, AlertTriangle, Copy, SkipForward,
} from 'lucide-react';
import { useStore } from '@/lib/store';
import { track } from '@/lib/telemetry';
import RoleGuard from '@/components/RoleGuard';
import { useToast } from '@/components/Toast';
import { PageHeader, GlassCard, Button, KpiTile, StatusBadge } from '@/components/ui';
import {
  useTrialActivation, ROLES, USE_CASES, OTP_LABEL, otpCode, preferredCategory, TRIAL_CREDITS,
  type Role, type UseCase,
} from '@/lib/trial-activation';

function ActivateInner() {
  const { user, activeKeys, generateFirstKey } = useStore();
  const toast = useToast();
  const email = user?.email ?? 'you@zinbit.zintlr.com';

  const ta = useTrialActivation();
  const [pickRole, setPickRole] = useState<Role | null>(ta.role);
  const [pickUseCase, setPickUseCase] = useState<UseCase | null>(ta.useCase);
  const [simulateFlagged, setSimulateFlagged] = useState(false);
  const [otp, setOtp] = useState('');
  const [issuedKey, setIssuedKey] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => { track('activation_viewed', {}); }, []);

  // PM auto-key: one-click provisioning the moment the trial is granted.
  useEffect(() => {
    if (ta.trialStatus === 'granted' && ta.isPM && !ta.autoKeyIssued && activeKeys.length === 0) {
      const k = generateFirstKey();
      ta.markAutoKeyIssued();
      setIssuedKey(k.key);
      track('trial_key_autogenerated', { pm: true });
      track('api_key_created', { source: 'pm-auto-key' });
    }
  }, [ta.trialStatus, ta.isPM, ta.autoKeyIssued, activeKeys.length, generateFirstKey, ta]);

  const step = !ta.profileComplete ? 1 : ta.trialStatus === 'none' ? 2 : ta.trialStatus === 'pending_otp' ? 3 : 4;
  const stepMeta = [
    { n: 1, label: 'Profile' },
    { n: 2, label: 'Avail trial' },
    { n: 3, label: 'Verify' },
    { n: 4, label: 'First key' },
  ];

  const saveProfile = () => {
    if (!pickRole || !pickUseCase) return;
    ta.setProfile(pickRole, pickUseCase);
    track('onboarding_profile_captured', { role: pickRole, useCase: pickUseCase, isPM: ROLES.find((r) => r.id === pickRole)?.isPM ?? false });
  };

  const avail = () => {
    const decision = ta.availTrial(email, simulateFlagged ? { disposableEmail: true } : undefined);
    track('trial_availed', { decision: decision.decision, score: decision.score });
    if (decision.decision === 'grant') { track('trial_granted_instant', {}); toast.success('Trial activated', `${TRIAL_CREDITS.toLocaleString()} free credits added.`); }
    else { track('otp_requested', { channel: 'sms' }); }
  };

  const verify = () => {
    if (ta.verifyOtp(email, otp)) { track('otp_verified', {}); toast.success('Verified', `${TRIAL_CREDITS.toLocaleString()} free credits added.`); }
    else toast.error('Incorrect code', 'Check the code and try again.');
  };
  const skip = () => { ta.skipOtp(); track('otp_skipped', {}); toast.info('Skipped verification', 'Trial activated — you can verify later.'); };
  const escalate = () => { ta.escalateOtp(); track('otp_channel_escalated', {}); };

  const genKey = () => {
    const k = generateFirstKey();
    ta.markAutoKeyIssued();
    setIssuedKey(k.key);
    track('trial_key_autogenerated', { pm: false });
    track('api_key_created', { source: 'activation' });
    toast.success('Key created', 'Your first API key is ready.');
  };

  const existingKey = activeKeys[0]?.key ?? null;
  const shownKey = issuedKey ?? existingKey;

  return (
    <div className="max-w-[900px] mx-auto pb-16">
      <PageHeader icon={<Rocket />} title="Activate your trial" description="A minute to set up: tell us what you’re building, claim your free credits, and get your first key. Public-API credits are free and spent before any paid balance." />

      {/* Stepper */}
      <div className="flex items-center gap-2 mt-6 mb-2 flex-wrap">
        {stepMeta.map((s, i) => (
          <div key={s.n} className="flex items-center gap-2">
            <div className={`flex items-center gap-2 rounded-full px-3 py-1.5 text-[12px] font-bold border ${step > s.n ? 'border-semantic-success/40 bg-semantic-success/10 text-semantic-success' : step === s.n ? 'border-teal/40 bg-teal/10 text-teal' : 'border-border bg-surface-2 text-fg-subtle'}`}>
              <span className="w-4 h-4 inline-flex items-center justify-center rounded-full bg-current/15">{step > s.n ? <Check className="w-3 h-3" /> : s.n}</span>
              {s.label}
            </div>
            {i < stepMeta.length - 1 && <span className="text-fg-subtle">·</span>}
          </div>
        ))}
      </div>

      <AnimatePresence mode="wait">
        {/* Step 1 — profile */}
        {step === 1 && (
          <motion.div key="s1" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}>
            <GlassCard className="p-5 mt-4">
              <h3 className="text-sm font-bold text-fg mb-1">What best describes you?</h3>
              <p className="text-[12px] text-fg-muted mb-3">Product Managers get a one-click key; everyone gets a catalogue tuned to their use-case.</p>
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                {ROLES.map((r) => (
                  <button key={r.id} onClick={() => setPickRole(r.id)}
                    className={`rounded-xl border px-3 py-3 text-left text-[13px] font-semibold transition-colors ${pickRole === r.id ? 'border-teal/50 bg-teal/10 text-fg' : 'border-border bg-surface-2 text-fg-muted hover:border-teal/30'}`}>
                    {r.label}{r.isPM && <span className="block text-[10px] font-bold text-teal mt-0.5">1-click key</span>}
                  </button>
                ))}
              </div>
              <h3 className="text-sm font-bold text-fg mt-5 mb-3">What will you use Zinbit for?</h3>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                {USE_CASES.map((u) => (
                  <button key={u.id} onClick={() => setPickUseCase(u.id)}
                    className={`rounded-xl border px-3 py-3 text-left text-[13px] font-semibold flex items-center gap-2 transition-colors ${pickUseCase === u.id ? 'border-teal/50 bg-teal/10 text-fg' : 'border-border bg-surface-2 text-fg-muted hover:border-teal/30'}`}>
                    <Target className="w-4 h-4 text-teal shrink-0" /> {u.label}
                  </button>
                ))}
              </div>
              <div className="mt-5">
                <Button onClick={saveProfile} disabled={!pickRole || !pickUseCase}>Continue <ArrowRight className="w-4 h-4" /></Button>
              </div>
            </GlassCard>
          </motion.div>
        )}

        {/* Step 2 — avail trial */}
        {step === 2 && (
          <motion.div key="s2" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}>
            <GlassCard className="p-5 mt-4">
              <div className="flex items-center gap-2 mb-3"><Sparkles className="w-4 h-4 text-teal" /><h3 className="text-sm font-bold text-fg">Claim your free trial</h3></div>
              <div className="grid grid-cols-2 lg:grid-cols-3 gap-3 mb-4">
                <KpiTile label="Free credits" value={TRIAL_CREDITS.toLocaleString()} icon={<Zap />} hint="Public APIs" />
                <KpiTile label="Tuned to" value={preferredCategory(ta.useCase)} icon={<Target />} hint="your use-case" />
                <KpiTile label="Card required" value="No" icon={<ShieldCheck />} />
              </div>
              <label className="flex items-center gap-2 text-[12px] text-fg-muted mb-4 cursor-pointer">
                <input type="checkbox" checked={simulateFlagged} onChange={(e) => setSimulateFlagged(e.target.checked)} className="accent-teal" />
                Simulate a flagged signup (forces the OTP path) <span className="text-fg-subtle">— demo of the risk gate</span>
              </label>
              <Button onClick={avail}><ShieldCheck className="w-4 h-4" /> Avail free trial</Button>
              <p className="text-[11px] text-fg-subtle mt-2">Low-risk signups get credits instantly; flagged ones verify a phone first (provisional risk rules pending final policy).</p>
            </GlassCard>
          </motion.div>
        )}

        {/* Step 3 — OTP */}
        {step === 3 && (
          <motion.div key="s3" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}>
            <GlassCard className="p-5 mt-4">
              <div className="flex items-center gap-2 mb-1"><Smartphone className="w-4 h-4 text-teal" /><h3 className="text-sm font-bold text-fg">Verify your phone</h3><StatusBadge tone="warning">flagged signup</StatusBadge></div>
              <p className="text-[12px] text-fg-muted mb-1">We sent a 6-digit code via <span className="font-semibold text-fg">{OTP_LABEL[ta.otpChannel ?? 'sms']}</span>. {ta.risk?.reasons[0] ? `Reason: ${ta.risk.reasons[0]}.` : ''}</p>
              <p className="text-[11px] text-fg-subtle mb-4">Prototype demo code: <code className="font-mono text-teal">{otpCode(email)}</code></p>
              <div className="flex gap-2 flex-wrap">
                <input value={otp} onChange={(e) => setOtp(e.target.value)} inputMode="numeric" maxLength={6} placeholder="••••••"
                  className="w-40 rounded-xl border border-border bg-surface-2 px-3 py-2.5 font-mono text-[15px] tracking-[0.3em] text-fg outline-none focus:border-teal/50" />
                <Button onClick={verify}><Check className="w-4 h-4" /> Verify</Button>
                <Button variant="secondary" onClick={escalate}><RefreshCw className="w-4 h-4" /> Try {OTP_LABEL[ta.otpChannel === 'sms' ? 'whatsapp' : 'call']}</Button>
                <Button variant="ghost" onClick={skip}><SkipForward className="w-4 h-4" /> Skip for now</Button>
              </div>
            </GlassCard>
          </motion.div>
        )}

        {/* Step 4 — granted + first key */}
        {step === 4 && (
          <motion.div key="s4" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}>
            <GlassCard className="p-5 mt-4 border-semantic-success/30 bg-semantic-success/5">
              <div className="flex items-center gap-2"><span className="text-semantic-success"><Check className="w-5 h-5" /></span><h3 className="text-sm font-bold text-fg">Trial active — {ta.trialCredits.toLocaleString()} free credits</h3></div>
              <p className="text-[12px] text-fg-muted mt-0.5">Public-API credits, spent before any paid balance. {ta.isPM ? 'As a PM, we generated your first key automatically.' : 'Generate your first key to make a call.'}</p>
            </GlassCard>

            <GlassCard className="p-5 mt-4">
              <div className="flex items-center gap-2 mb-3"><KeyRound className="w-4 h-4 text-teal" /><h3 className="text-sm font-bold text-fg">Your first API key</h3></div>
              {shownKey ? (
                <>
                  <div className="flex items-center gap-2 flex-wrap">
                    <code className="font-mono text-[13px] text-fg bg-surface-2 border border-border rounded-lg px-3 py-2 break-all">{shownKey}</code>
                    <Button variant="ghost" size="sm" onClick={() => { navigator.clipboard?.writeText(shownKey).then(() => { setCopied(true); setTimeout(() => setCopied(false), 1200); }).catch(() => {}); }}>
                      {copied ? <Check className="w-4 h-4 text-teal" /> : <Copy className="w-4 h-4" />} Copy
                    </Button>
                  </div>
                  {issuedKey && <p className="text-[11px] text-semantic-warning mt-2 flex items-center gap-1"><AlertTriangle className="w-3 h-3" /> Shown once — copy it now.</p>}
                  <div className="mt-4 flex items-center gap-3">
                    <Link href="/console/explorer"><Button size="sm">Make your first call <ArrowRight className="w-4 h-4" /></Button></Link>
                    <Link href="/console/keys" className="text-xs font-bold text-fg-muted hover:text-teal transition-colors">Manage keys</Link>
                  </div>
                </>
              ) : (
                <Button onClick={genKey}><KeyRound className="w-4 h-4" /> Generate your first key</Button>
              )}
            </GlassCard>
          </motion.div>
        )}
      </AnimatePresence>

      <div className="mt-5 flex items-center gap-4">
        <Link href="/console/funnel" className="text-xs font-bold text-fg-muted hover:text-teal transition-colors inline-flex items-center gap-1">Funnel <ArrowRight className="w-3.5 h-3.5" /></Link>
        {ta.trialStatus !== 'none' && <button onClick={() => { ta.reset(); setPickRole(null); setPickUseCase(null); setOtp(''); setIssuedKey(null); }} className="text-xs font-bold text-fg-subtle hover:text-fg transition-colors">Reset activation (demo)</button>}
      </div>
    </div>
  );
}

export default function ActivatePage() {
  return (
    <RoleGuard allowedRoles={['admin', 'developer', 'billing']}>
      <ActivateInner />
    </RoleGuard>
  );
}
