/**
 * Partner & Affiliate Revenue-Sharing Engine
 * Tracks partner referrals, calculates tiered commissions, and manages payouts.
 * Supports: Resellers, Referral Affiliates, White-Label OEM Partners, Technology Partners.
 */

// ─── Types ────────────────────────────────────────────────────────────────────

export type PartnerTier = 'affiliate' | 'silver' | 'gold' | 'platinum' | 'oem';
export type CommissionType = 'percentage' | 'flat_per_call' | 'revenue_share';
export type PayoutStatus = 'pending' | 'approved' | 'paid' | 'held';
export type RevenueEventType = 'api_call' | 'subscription_upgrade' | 'contract_signed' | 'renewal';

export interface PartnerRecord {
  partnerId: string;
  name: string;
  tier: PartnerTier;
  referralCode: string;
  commissionConfig: CommissionConfig;
  cumulativeRevenue: number;   // Total revenue generated by this partner's referrals
  cumulativeEarnings: number;  // Total commission earned (lifetime)
  pendingPayout: number;       // Unpaid balance
  joinedAt: number;
}

export interface CommissionConfig {
  type: CommissionType;
  /** For 'percentage' and 'revenue_share': e.g. 0.2 = 20% */
  rate: number;
  /** For 'flat_per_call': USD per credit consumed */
  flatRatePerCredit?: number;
  /** Hard cap per calendar month in USD */
  monthlyCap?: number;
  /** Bonus threshold: extra % if partner drives > $X/month */
  acceleratorThreshold?: number;
  acceleratorBonus?: number;
}

export interface RevenueEvent {
  eventId: string;
  partnerId: string;
  referredApiKey: string;  // The end-customer's key that was referred by this partner
  eventType: RevenueEventType;
  grossRevenue: number;    // USD gross revenue from end-customer
  creditsConsumed?: number;
  commissionEarned: number;
  timestamp: number;
}

export interface PayoutRecord {
  payoutId: string;
  partnerId: string;
  amount: number;
  status: PayoutStatus;
  periodStart: number;
  periodEnd: number;
  events: string[];  // eventIds included in this payout
  createdAt: number;
  paidAt?: number;
}

export interface PartnerDashboard {
  partner: PartnerRecord;
  thisMonthRevenue: number;
  thisMonthEarnings: number;
  projectedPayout: number;
  recentEvents: RevenueEvent[];
  pendingPayouts: PayoutRecord[];
  acceleratorUnlocked: boolean;
  nextTierAt?: number;  // Revenue needed to unlock next tier
}

// ─── Tier Commission Schedules ─────────────────────────────────────────────────

const TIER_DEFAULTS: Record<PartnerTier, CommissionConfig> = {
  affiliate: {
    type: 'percentage',
    rate: 0.10, // 10% of referred customer's spend
    monthlyCap: 2000,
    acceleratorThreshold: 5000,
    acceleratorBonus: 0.05, // +5% if they drive >$5k/mo
  },
  silver: {
    type: 'percentage',
    rate: 0.15, // 15%
    monthlyCap: 10000,
    acceleratorThreshold: 20000,
    acceleratorBonus: 0.05,
  },
  gold: {
    type: 'percentage',
    rate: 0.20, // 20%
    monthlyCap: 50000,
    acceleratorThreshold: 100000,
    acceleratorBonus: 0.03,
  },
  platinum: {
    type: 'revenue_share',
    rate: 0.25, // 25% revenue share — true co-sell model
    monthlyCap: undefined, // Uncapped
    acceleratorThreshold: 500000,
    acceleratorBonus: 0.02,
  },
  oem: {
    type: 'flat_per_call',
    rate: 0,
    flatRatePerCredit: 0.0008, // $0.0008 per credit consumed by resold customer
    monthlyCap: undefined,
  },
};

// Tier upgrade thresholds (lifetime referred revenue)
const TIER_THRESHOLDS: Record<PartnerTier, number> = {
  affiliate: 0,
  silver: 10_000,
  gold: 100_000,
  platinum: 500_000,
  oem: Infinity, // OEM is invite-only
};

// ─── In-Memory Stores ──────────────────────────────────────────────────────────

const partnerRegistry = new Map<string, PartnerRecord>();
const referralIndex = new Map<string, string>(); // referralCode -> partnerId
const apiKeyPartnerIndex = new Map<string, string>(); // referredApiKey -> partnerId
const revenueEvents: RevenueEvent[] = [];
const payoutLedger = new Map<string, PayoutRecord[]>(); // partnerId -> payouts

// ─── Seed Mock Partners ────────────────────────────────────────────────────────

function seedPartners() {
  const partners: PartnerRecord[] = [
    {
      partnerId: 'prt_apollo_io',
      name: 'Apollo.io Integration Partner',
      tier: 'platinum',
      referralCode: 'APOLLO2026',
      commissionConfig: TIER_DEFAULTS.platinum,
      cumulativeRevenue: 1_250_000,
      cumulativeEarnings: 287_500,
      pendingPayout: 18_400,
      joinedAt: Date.now() - 365 * 24 * 60 * 60 * 1000,
    },
    {
      partnerId: 'prt_hubspot',
      name: 'HubSpot App Marketplace',
      tier: 'gold',
      referralCode: 'HUBSPOT26',
      commissionConfig: TIER_DEFAULTS.gold,
      cumulativeRevenue: 340_000,
      cumulativeEarnings: 72_000,
      pendingPayout: 6_200,
      joinedAt: Date.now() - 180 * 24 * 60 * 60 * 1000,
    },
    {
      partnerId: 'prt_accel_ventures',
      name: 'Accel Ventures (VC Referral)',
      tier: 'silver',
      referralCode: 'ACCEL26',
      commissionConfig: TIER_DEFAULTS.silver,
      cumulativeRevenue: 42_000,
      cumulativeEarnings: 6_900,
      pendingPayout: 2_100,
      joinedAt: Date.now() - 90 * 24 * 60 * 60 * 1000,
    },
    {
      partnerId: 'prt_indie_dev_01',
      name: 'IndieHacker Affiliate',
      tier: 'affiliate',
      referralCode: 'INDIEHACK',
      commissionConfig: TIER_DEFAULTS.affiliate,
      cumulativeRevenue: 4_800,
      cumulativeEarnings: 480,
      pendingPayout: 180,
      joinedAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
    },
  ];

  for (const p of partners) {
    partnerRegistry.set(p.partnerId, p);
    referralIndex.set(p.referralCode.toUpperCase(), p.partnerId);
  }
}

seedPartners();

// ─── Core Functions ─────────────────────────────────────────────────────────

function generateId(prefix: string): string {
  return `${prefix}_${Date.now()}_${Math.random().toString(36).substring(2, 8)}`;
}

/**
 * Calculate commission for a revenue event based on partner's tier config.
 */
export function calculateCommission(
  partner: PartnerRecord,
  grossRevenue: number,
  creditsConsumed: number = 0,
  currentMonthEarnings: number = 0
): number {
  const cfg = partner.commissionConfig;
  let commission = 0;

  if (cfg.type === 'percentage' || cfg.type === 'revenue_share') {
    commission = grossRevenue * cfg.rate;

    // Accelerator bonus check
    if (cfg.acceleratorThreshold && cfg.acceleratorBonus) {
      const monthlyRevenue = partner.cumulativeRevenue; // simplified
      if (monthlyRevenue > cfg.acceleratorThreshold) {
        commission += grossRevenue * cfg.acceleratorBonus;
      }
    }
  } else if (cfg.type === 'flat_per_call' && cfg.flatRatePerCredit) {
    commission = creditsConsumed * cfg.flatRatePerCredit;
  }

  // Monthly cap enforcement
  if (cfg.monthlyCap) {
    const headroom = cfg.monthlyCap - currentMonthEarnings;
    commission = Math.min(commission, Math.max(0, headroom));
  }

  return Math.round(commission * 100) / 100;
}

/**
 * Attribute an API key to a partner via referral code (called at key creation).
 */
export function attributeReferral(
  apiKey: string,
  referralCode: string
): { success: boolean; partnerId?: string; partnerName?: string } {
  const partnerId = referralIndex.get(referralCode.toUpperCase());
  if (!partnerId) {
    return { success: false };
  }
  apiKeyPartnerIndex.set(apiKey, partnerId);
  return { success: true, partnerId, partnerName: partnerRegistry.get(partnerId)?.name };
}

/**
 * Record a revenue event and credit the partner's commission ledger.
 */
export function recordRevenueEvent(
  apiKey: string,
  eventType: RevenueEventType,
  grossRevenue: number,
  creditsConsumed: number = 0
): RevenueEvent | null {
  const partnerId = apiKeyPartnerIndex.get(apiKey);
  if (!partnerId) return null;

  const partner = partnerRegistry.get(partnerId);
  if (!partner) return null;

  const commission = calculateCommission(partner, grossRevenue, creditsConsumed);

  const event: RevenueEvent = {
    eventId: generateId('evt'),
    partnerId,
    referredApiKey: apiKey,
    eventType,
    grossRevenue,
    creditsConsumed,
    commissionEarned: commission,
    timestamp: Date.now(),
  };

  revenueEvents.push(event);

  // Update partner ledger
  partner.cumulativeRevenue += grossRevenue;
  partner.cumulativeEarnings += commission;
  partner.pendingPayout += commission;

  // Auto tier upgrade check
  partner.tier = computeTier(partner.cumulativeRevenue);

  partnerRegistry.set(partnerId, partner);
  return event;
}

function computeTier(cumulativeRevenue: number): PartnerTier {
  if (cumulativeRevenue >= TIER_THRESHOLDS.gold) return 'gold';
  if (cumulativeRevenue >= TIER_THRESHOLDS.silver) return 'silver';
  return 'affiliate';
}

/**
 * Get a full partner dashboard with this month's stats, projections, and payout queue.
 */
export function getPartnerDashboard(partnerId: string): PartnerDashboard | null {
  const partner = partnerRegistry.get(partnerId);
  if (!partner) return null;

  const now = Date.now();
  const monthStart = new Date();
  monthStart.setDate(1);
  monthStart.setHours(0, 0, 0, 0);

  const thisMonthEvents = revenueEvents.filter(
    e => e.partnerId === partnerId && e.timestamp >= monthStart.getTime()
  );

  const thisMonthRevenue = thisMonthEvents.reduce((s, e) => s + e.grossRevenue, 0);
  const thisMonthEarnings = thisMonthEvents.reduce((s, e) => s + e.commissionEarned, 0);

  const cfg = partner.commissionConfig;
  const acceleratorUnlocked = !!(
    cfg.acceleratorThreshold && thisMonthRevenue >= cfg.acceleratorThreshold
  );

  const nextTierEntry = Object.entries(TIER_THRESHOLDS).find(
    ([tier, threshold]) =>
      TIER_THRESHOLDS[tier as PartnerTier] > partner.cumulativeRevenue && tier !== 'oem'
  );
  const nextTierAt = nextTierEntry
    ? nextTierEntry[1] - partner.cumulativeRevenue
    : undefined;

  const pendingPayouts = (payoutLedger.get(partnerId) || []).filter(
    p => p.status === 'pending' || p.status === 'approved'
  );

  return {
    partner,
    thisMonthRevenue,
    thisMonthEarnings,
    projectedPayout: partner.pendingPayout,
    recentEvents: revenueEvents.filter(e => e.partnerId === partnerId).slice(-10),
    pendingPayouts,
    acceleratorUnlocked,
    nextTierAt,
  };
}

/**
 * Process month-end payout batch for all partners.
 * In production, this triggers ACH/SWIFT or Stripe Connect payouts.
 */
export function processMonthEndPayouts(): PayoutRecord[] {
  const now = Date.now();
  const periodEnd = now;
  const periodStart = now - 30 * 24 * 60 * 60 * 1000;
  const processed: PayoutRecord[] = [];

  for (const [partnerId, partner] of partnerRegistry) {
    if (partner.pendingPayout < 100) continue; // Minimum payout threshold: $100

    const relevantEvents = revenueEvents
      .filter(e => e.partnerId === partnerId && e.timestamp >= periodStart && e.timestamp <= periodEnd)
      .map(e => e.eventId);

    const payout: PayoutRecord = {
      payoutId: generateId('pay'),
      partnerId,
      amount: partner.pendingPayout,
      status: 'approved',
      periodStart,
      periodEnd,
      events: relevantEvents,
      createdAt: now,
    };

    const existing = payoutLedger.get(partnerId) || [];
    existing.push(payout);
    payoutLedger.set(partnerId, existing);

    partner.pendingPayout = 0; // Clear balance after payout
    partnerRegistry.set(partnerId, partner);
    processed.push(payout);
  }

  return processed;
}

/**
 * Lookup a partner by referral code or partner ID.
 */
export function lookupPartner(query: string): PartnerRecord | null {
  // Try direct ID lookup
  if (partnerRegistry.has(query)) return partnerRegistry.get(query)!;
  // Try referral code
  const byCode = referralIndex.get(query.toUpperCase());
  if (byCode) return partnerRegistry.get(byCode) || null;
  return null;
}

export function getAllPartners(): PartnerRecord[] {
  return Array.from(partnerRegistry.values());
}
